# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

lane :aws_device_run_android do
  ENV['AWS_ACCESS_KEY_ID']     = '1234'
  ENV['AWS_SECRET_ACCESS_KEY'] = 'xyz'
  ENV['AWS_REGION']            = 'us-west-2'
  ENV['AWS_REGION']            = 'us-west-2'


  #Build Debug App + Instrumentation Apk
  gradle(task: 'assembleDebug')
  gradle(task: 'assembleAndroidTest')

  sh("ls")

  # RUN tests on AWS Device Farm
  aws_device_farm(
    name:                  'Testing-Demo',
    test_binary_path:      '/Users/inehemias/Documents/AndroidArchitectureProjects/TestingDemoCopy/Espresso-Test-Project/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
    binary_path:           '/Users/inehemias/Documents/AndroidArchitectureProjects/TestingDemoCopy/Espresso-Test-Project/app/build/outputs/apk/debug/app-debug.apk',
    
    device_pool:         'SingleDevice',
    wait_for_completion: true,
    verbose: true,
    print_web_url_of_run: true,

  )
end